name: intent-entity-train-val
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: model_training
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt
            cd morphine && wget ${{ secrets.DATA_PATH }} && python trainer.py

            # Write your CML report
            cml-send-comment report.md

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Docker Image Build and Push
        run: |
            docker build -t docker.pkg.github.com/cheesama/morphine-sklearn/morphine:${{ steps.date.outputs.date }}
            docker push docker.pkg.github.com/cheesama/morphine-sklearn/morphine:${{ steps.date.outputs.date }}
