name: intent-entity-train-val
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: model_training
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt
            cd morphine && wget ${{ secrets.DATA_PATH }} && python trainer.py

            # Write your CML report
            cml-send-comment report.md

            echo "::set-env name=REPORT::$(cat report.md)"

      - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: cheesama/morphine-sklearn/morphine
            tag_with_ref: true
            # docker login https://docker.pkg.github.com -u USERNAME --password-stdin
            
      - name: Validataion Result Slack notification
        uses: tokorom/action-slack-incoming-webhook@master
        env: 
            INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
            text: Check Validation Report
            attachments: |
                [
                    {
                        "author_name": "${{ github.actor }}",
                        "author_link": "http://github.com/cheesama",
                        "fields":[
                            {
                                "title": "Below is valid set classification report",
                                "value": "${{ env.REPORT }}",
                                "short": false
                            }
                        ]
                    }
                ]



